export interface CountryPhoneInfo {
  prefix: string;
  country: string;
  code: string;
  flag: string;
}

export const phoneCountryCodes: CountryPhoneInfo[] = [
  { prefix: "+1242", country: "Bahamas", code: "BS", flag: "🇧🇸" },
  { prefix: "+1246", country: "Barbados", code: "BB", flag: "🇧🇧" },
  { prefix: "+1264", country: "Anguilla", code: "AI", flag: "🇦🇮" },
  { prefix: "+1268", country: "Antigua and Barbuda", code: "AG", flag: "🇦🇬" },
  { prefix: "+1284", country: "British Virgin Islands", code: "VG", flag: "🇻🇬" },
  { prefix: "+1340", country: "US Virgin Islands", code: "VI", flag: "🇻🇮" },
  { prefix: "+1345", country: "Cayman Islands", code: "KY", flag: "🇰🇾" },
  { prefix: "+1441", country: "Bermuda", code: "BM", flag: "🇧🇲" },
  { prefix: "+1473", country: "Grenada", code: "GD", flag: "🇬🇩" },
  { prefix: "+1649", country: "Turks and Caicos", code: "TC", flag: "🇹🇨" },
  { prefix: "+1664", country: "Montserrat", code: "MS", flag: "🇲🇸" },
  { prefix: "+1670", country: "Northern Mariana Islands", code: "MP", flag: "🇲🇵" },
  { prefix: "+1671", country: "Guam", code: "GU", flag: "🇬🇺" },
  { prefix: "+1684", country: "American Samoa", code: "AS", flag: "🇦🇸" },
  { prefix: "+1721", country: "Sint Maarten", code: "SX", flag: "🇸🇽" },
  { prefix: "+1758", country: "Saint Lucia", code: "LC", flag: "🇱🇨" },
  { prefix: "+1767", country: "Dominica", code: "DM", flag: "🇩🇲" },
  { prefix: "+1784", country: "St. Vincent & Grenadines", code: "VC", flag: "🇻🇨" },
  { prefix: "+1787", country: "Puerto Rico", code: "PR", flag: "🇵🇷" },
  { prefix: "+1809", country: "Dominican Republic", code: "DO", flag: "🇩🇴" },
  { prefix: "+1868", country: "Trinidad and Tobago", code: "TT", flag: "🇹🇹" },
  { prefix: "+1869", country: "St. Kitts and Nevis", code: "KN", flag: "🇰🇳" },
  { prefix: "+1876", country: "Jamaica", code: "JM", flag: "🇯🇲" },
  { prefix: "+1", country: "United States / Canada", code: "US", flag: "🇺🇸" },
  { prefix: "+20", country: "Egypt", code: "EG", flag: "🇪🇬" },
  { prefix: "+211", country: "South Sudan", code: "SS", flag: "🇸🇸" },
  { prefix: "+212", country: "Morocco", code: "MA", flag: "🇲🇦" },
  { prefix: "+213", country: "Algeria", code: "DZ", flag: "🇩🇿" },
  { prefix: "+216", country: "Tunisia", code: "TN", flag: "🇹🇳" },
  { prefix: "+218", country: "Libya", code: "LY", flag: "🇱🇾" },
  { prefix: "+220", country: "Gambia", code: "GM", flag: "🇬🇲" },
  { prefix: "+221", country: "Senegal", code: "SN", flag: "🇸🇳" },
  { prefix: "+222", country: "Mauritania", code: "MR", flag: "🇲🇷" },
  { prefix: "+223", country: "Mali", code: "ML", flag: "🇲🇱" },
  { prefix: "+224", country: "Guinea", code: "GN", flag: "🇬🇳" },
  { prefix: "+225", country: "Ivory Coast", code: "CI", flag: "🇨🇮" },
  { prefix: "+226", country: "Burkina Faso", code: "BF", flag: "🇧🇫" },
  { prefix: "+227", country: "Niger", code: "NE", flag: "🇳🇪" },
  { prefix: "+228", country: "Togo", code: "TG", flag: "🇹🇬" },
  { prefix: "+229", country: "Benin", code: "BJ", flag: "🇧🇯" },
  { prefix: "+230", country: "Mauritius", code: "MU", flag: "🇲🇺" },
  { prefix: "+231", country: "Liberia", code: "LR", flag: "🇱🇷" },
  { prefix: "+232", country: "Sierra Leone", code: "SL", flag: "🇸🇱" },
  { prefix: "+233", country: "Ghana", code: "GH", flag: "🇬🇭" },
  { prefix: "+234", country: "Nigeria", code: "NG", flag: "🇳🇬" },
  { prefix: "+235", country: "Chad", code: "TD", flag: "🇹🇩" },
  { prefix: "+236", country: "Central African Republic", code: "CF", flag: "🇨🇫" },
  { prefix: "+237", country: "Cameroon", code: "CM", flag: "🇨🇲" },
  { prefix: "+238", country: "Cape Verde", code: "CV", flag: "🇨🇻" },
  { prefix: "+239", country: "São Tomé and Príncipe", code: "ST", flag: "🇸🇹" },
  { prefix: "+240", country: "Equatorial Guinea", code: "GQ", flag: "🇬🇶" },
  { prefix: "+241", country: "Gabon", code: "GA", flag: "🇬🇦" },
  { prefix: "+242", country: "Republic of Congo", code: "CG", flag: "🇨🇬" },
  { prefix: "+243", country: "DR Congo", code: "CD", flag: "🇨🇩" },
  { prefix: "+244", country: "Angola", code: "AO", flag: "🇦🇴" },
  { prefix: "+245", country: "Guinea-Bissau", code: "GW", flag: "🇬🇼" },
  { prefix: "+246", country: "British Indian Ocean Territory", code: "IO", flag: "🇮🇴" },
  { prefix: "+247", country: "Ascension Island", code: "AC", flag: "🇦🇨" },
  { prefix: "+248", country: "Seychelles", code: "SC", flag: "🇸🇨" },
  { prefix: "+249", country: "Sudan", code: "SD", flag: "🇸🇩" },
  { prefix: "+250", country: "Rwanda", code: "RW", flag: "🇷🇼" },
  { prefix: "+251", country: "Ethiopia", code: "ET", flag: "🇪🇹" },
  { prefix: "+252", country: "Somalia", code: "SO", flag: "🇸🇴" },
  { prefix: "+253", country: "Djibouti", code: "DJ", flag: "🇩🇯" },
  { prefix: "+254", country: "Kenya", code: "KE", flag: "🇰🇪" },
  { prefix: "+255", country: "Tanzania", code: "TZ", flag: "🇹🇿" },
  { prefix: "+256", country: "Uganda", code: "UG", flag: "🇺🇬" },
  { prefix: "+257", country: "Burundi", code: "BI", flag: "🇧🇮" },
  { prefix: "+258", country: "Mozambique", code: "MZ", flag: "🇲🇿" },
  { prefix: "+260", country: "Zambia", code: "ZM", flag: "🇿🇲" },
  { prefix: "+261", country: "Madagascar", code: "MG", flag: "🇲🇬" },
  { prefix: "+262", country: "Réunion", code: "RE", flag: "🇷🇪" },
  { prefix: "+263", country: "Zimbabwe", code: "ZW", flag: "🇿🇼" },
  { prefix: "+264", country: "Namibia", code: "NA", flag: "🇳🇦" },
  { prefix: "+265", country: "Malawi", code: "MW", flag: "🇲🇼" },
  { prefix: "+266", country: "Lesotho", code: "LS", flag: "🇱🇸" },
  { prefix: "+267", country: "Botswana", code: "BW", flag: "🇧🇼" },
  { prefix: "+268", country: "Eswatini", code: "SZ", flag: "🇸🇿" },
  { prefix: "+269", country: "Comoros", code: "KM", flag: "🇰🇲" },
  { prefix: "+27", country: "South Africa", code: "ZA", flag: "🇿🇦" },
  { prefix: "+290", country: "Saint Helena", code: "SH", flag: "🇸🇭" },
  { prefix: "+291", country: "Eritrea", code: "ER", flag: "🇪🇷" },
  { prefix: "+297", country: "Aruba", code: "AW", flag: "🇦🇼" },
  { prefix: "+298", country: "Faroe Islands", code: "FO", flag: "🇫🇴" },
  { prefix: "+299", country: "Greenland", code: "GL", flag: "🇬🇱" },
  { prefix: "+30", country: "Greece", code: "GR", flag: "🇬🇷" },
  { prefix: "+31", country: "Netherlands", code: "NL", flag: "🇳🇱" },
  { prefix: "+32", country: "Belgium", code: "BE", flag: "🇧🇪" },
  { prefix: "+33", country: "France", code: "FR", flag: "🇫🇷" },
  { prefix: "+34", country: "Spain", code: "ES", flag: "🇪🇸" },
  { prefix: "+350", country: "Gibraltar", code: "GI", flag: "🇬🇮" },
  { prefix: "+351", country: "Portugal", code: "PT", flag: "🇵🇹" },
  { prefix: "+352", country: "Luxembourg", code: "LU", flag: "🇱🇺" },
  { prefix: "+353", country: "Ireland", code: "IE", flag: "🇮🇪" },
  { prefix: "+354", country: "Iceland", code: "IS", flag: "🇮🇸" },
  { prefix: "+355", country: "Albania", code: "AL", flag: "🇦🇱" },
  { prefix: "+356", country: "Malta", code: "MT", flag: "🇲🇹" },
  { prefix: "+357", country: "Cyprus", code: "CY", flag: "🇨🇾" },
  { prefix: "+358", country: "Finland", code: "FI", flag: "🇫🇮" },
  { prefix: "+359", country: "Bulgaria", code: "BG", flag: "🇧🇬" },
  { prefix: "+36", country: "Hungary", code: "HU", flag: "🇭🇺" },
  { prefix: "+370", country: "Lithuania", code: "LT", flag: "🇱🇹" },
  { prefix: "+371", country: "Latvia", code: "LV", flag: "🇱🇻" },
  { prefix: "+372", country: "Estonia", code: "EE", flag: "🇪🇪" },
  { prefix: "+373", country: "Moldova", code: "MD", flag: "🇲🇩" },
  { prefix: "+374", country: "Armenia", code: "AM", flag: "🇦🇲" },
  { prefix: "+375", country: "Belarus", code: "BY", flag: "🇧🇾" },
  { prefix: "+376", country: "Andorra", code: "AD", flag: "🇦🇩" },
  { prefix: "+377", country: "Monaco", code: "MC", flag: "🇲🇨" },
  { prefix: "+378", country: "San Marino", code: "SM", flag: "🇸🇲" },
  { prefix: "+380", country: "Ukraine", code: "UA", flag: "🇺🇦" },
  { prefix: "+381", country: "Serbia", code: "RS", flag: "🇷🇸" },
  { prefix: "+382", country: "Montenegro", code: "ME", flag: "🇲🇪" },
  { prefix: "+383", country: "Kosovo", code: "XK", flag: "🇽🇰" },
  { prefix: "+385", country: "Croatia", code: "HR", flag: "🇭🇷" },
  { prefix: "+386", country: "Slovenia", code: "SI", flag: "🇸🇮" },
  { prefix: "+387", country: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦" },
  { prefix: "+389", country: "North Macedonia", code: "MK", flag: "🇲🇰" },
  { prefix: "+39", country: "Italy", code: "IT", flag: "🇮🇹" },
  { prefix: "+40", country: "Romania", code: "RO", flag: "🇷🇴" },
  { prefix: "+41", country: "Switzerland", code: "CH", flag: "🇨🇭" },
  { prefix: "+420", country: "Czech Republic", code: "CZ", flag: "🇨🇿" },
  { prefix: "+421", country: "Slovakia", code: "SK", flag: "🇸🇰" },
  { prefix: "+423", country: "Liechtenstein", code: "LI", flag: "🇱🇮" },
  { prefix: "+43", country: "Austria", code: "AT", flag: "🇦🇹" },
  { prefix: "+44", country: "United Kingdom", code: "GB", flag: "🇬🇧" },
  { prefix: "+45", country: "Denmark", code: "DK", flag: "🇩🇰" },
  { prefix: "+46", country: "Sweden", code: "SE", flag: "🇸🇪" },
  { prefix: "+47", country: "Norway", code: "NO", flag: "🇳🇴" },
  { prefix: "+48", country: "Poland", code: "PL", flag: "🇵🇱" },
  { prefix: "+49", country: "Germany", code: "DE", flag: "🇩🇪" },
  { prefix: "+500", country: "Falkland Islands", code: "FK", flag: "🇫🇰" },
  { prefix: "+501", country: "Belize", code: "BZ", flag: "🇧🇿" },
  { prefix: "+502", country: "Guatemala", code: "GT", flag: "🇬🇹" },
  { prefix: "+503", country: "El Salvador", code: "SV", flag: "🇸🇻" },
  { prefix: "+504", country: "Honduras", code: "HN", flag: "🇭🇳" },
  { prefix: "+505", country: "Nicaragua", code: "NI", flag: "🇳🇮" },
  { prefix: "+506", country: "Costa Rica", code: "CR", flag: "🇨🇷" },
  { prefix: "+507", country: "Panama", code: "PA", flag: "🇵🇦" },
  { prefix: "+508", country: "Saint Pierre and Miquelon", code: "PM", flag: "🇵🇲" },
  { prefix: "+509", country: "Haiti", code: "HT", flag: "🇭🇹" },
  { prefix: "+51", country: "Peru", code: "PE", flag: "🇵🇪" },
  { prefix: "+52", country: "Mexico", code: "MX", flag: "🇲🇽" },
  { prefix: "+53", country: "Cuba", code: "CU", flag: "🇨🇺" },
  { prefix: "+54", country: "Argentina", code: "AR", flag: "🇦🇷" },
  { prefix: "+55", country: "Brazil", code: "BR", flag: "🇧🇷" },
  { prefix: "+56", country: "Chile", code: "CL", flag: "🇨🇱" },
  { prefix: "+57", country: "Colombia", code: "CO", flag: "🇨🇴" },
  { prefix: "+58", country: "Venezuela", code: "VE", flag: "🇻🇪" },
  { prefix: "+590", country: "Guadeloupe", code: "GP", flag: "🇬🇵" },
  { prefix: "+591", country: "Bolivia", code: "BO", flag: "🇧🇴" },
  { prefix: "+592", country: "Guyana", code: "GY", flag: "🇬🇾" },
  { prefix: "+593", country: "Ecuador", code: "EC", flag: "🇪🇨" },
  { prefix: "+594", country: "French Guiana", code: "GF", flag: "🇬🇫" },
  { prefix: "+595", country: "Paraguay", code: "PY", flag: "🇵🇾" },
  { prefix: "+596", country: "Martinique", code: "MQ", flag: "🇲🇶" },
  { prefix: "+597", country: "Suriname", code: "SR", flag: "🇸🇷" },
  { prefix: "+598", country: "Uruguay", code: "UY", flag: "🇺🇾" },
  { prefix: "+599", country: "Curaçao", code: "CW", flag: "🇨🇼" },
  { prefix: "+60", country: "Malaysia", code: "MY", flag: "🇲🇾" },
  { prefix: "+61", country: "Australia", code: "AU", flag: "🇦🇺" },
  { prefix: "+62", country: "Indonesia", code: "ID", flag: "🇮🇩" },
  { prefix: "+63", country: "Philippines", code: "PH", flag: "🇵🇭" },
  { prefix: "+64", country: "New Zealand", code: "NZ", flag: "🇳🇿" },
  { prefix: "+65", country: "Singapore", code: "SG", flag: "🇸🇬" },
  { prefix: "+66", country: "Thailand", code: "TH", flag: "🇹🇭" },
  { prefix: "+670", country: "Timor-Leste", code: "TL", flag: "🇹🇱" },
  { prefix: "+672", country: "Norfolk Island", code: "NF", flag: "🇳🇫" },
  { prefix: "+673", country: "Brunei", code: "BN", flag: "🇧🇳" },
  { prefix: "+674", country: "Nauru", code: "NR", flag: "🇳🇷" },
  { prefix: "+675", country: "Papua New Guinea", code: "PG", flag: "🇵🇬" },
  { prefix: "+676", country: "Tonga", code: "TO", flag: "🇹🇴" },
  { prefix: "+677", country: "Solomon Islands", code: "SB", flag: "🇸🇧" },
  { prefix: "+678", country: "Vanuatu", code: "VU", flag: "🇻🇺" },
  { prefix: "+679", country: "Fiji", code: "FJ", flag: "🇫🇯" },
  { prefix: "+680", country: "Palau", code: "PW", flag: "🇵🇼" },
  { prefix: "+681", country: "Wallis and Futuna", code: "WF", flag: "🇼🇫" },
  { prefix: "+682", country: "Cook Islands", code: "CK", flag: "🇨🇰" },
  { prefix: "+683", country: "Niue", code: "NU", flag: "🇳🇺" },
  { prefix: "+685", country: "Samoa", code: "WS", flag: "🇼🇸" },
  { prefix: "+686", country: "Kiribati", code: "KI", flag: "🇰🇮" },
  { prefix: "+687", country: "New Caledonia", code: "NC", flag: "🇳🇨" },
  { prefix: "+688", country: "Tuvalu", code: "TV", flag: "🇹🇻" },
  { prefix: "+689", country: "French Polynesia", code: "PF", flag: "🇵🇫" },
  { prefix: "+690", country: "Tokelau", code: "TK", flag: "🇹🇰" },
  { prefix: "+691", country: "Micronesia", code: "FM", flag: "🇫🇲" },
  { prefix: "+692", country: "Marshall Islands", code: "MH", flag: "🇲🇭" },
  { prefix: "+7", country: "Russia / Kazakhstan", code: "RU", flag: "🇷🇺" },
  { prefix: "+81", country: "Japan", code: "JP", flag: "🇯🇵" },
  { prefix: "+82", country: "South Korea", code: "KR", flag: "🇰🇷" },
  { prefix: "+84", country: "Vietnam", code: "VN", flag: "🇻🇳" },
  { prefix: "+850", country: "North Korea", code: "KP", flag: "🇰🇵" },
  { prefix: "+852", country: "Hong Kong", code: "HK", flag: "🇭🇰" },
  { prefix: "+853", country: "Macau", code: "MO", flag: "🇲🇴" },
  { prefix: "+855", country: "Cambodia", code: "KH", flag: "🇰🇭" },
  { prefix: "+856", country: "Laos", code: "LA", flag: "🇱🇦" },
  { prefix: "+86", country: "China", code: "CN", flag: "🇨🇳" },
  { prefix: "+880", country: "Bangladesh", code: "BD", flag: "🇧🇩" },
  { prefix: "+886", country: "Taiwan", code: "TW", flag: "🇹🇼" },
  { prefix: "+90", country: "Turkey", code: "TR", flag: "🇹🇷" },
  { prefix: "+91", country: "India", code: "IN", flag: "🇮🇳" },
  { prefix: "+92", country: "Pakistan", code: "PK", flag: "🇵🇰" },
  { prefix: "+93", country: "Afghanistan", code: "AF", flag: "🇦🇫" },
  { prefix: "+94", country: "Sri Lanka", code: "LK", flag: "🇱🇰" },
  { prefix: "+95", country: "Myanmar", code: "MM", flag: "🇲🇲" },
  { prefix: "+960", country: "Maldives", code: "MV", flag: "🇲🇻" },
  { prefix: "+961", country: "Lebanon", code: "LB", flag: "🇱🇧" },
  { prefix: "+962", country: "Jordan", code: "JO", flag: "🇯🇴" },
  { prefix: "+963", country: "Syria", code: "SY", flag: "🇸🇾" },
  { prefix: "+964", country: "Iraq", code: "IQ", flag: "🇮🇶" },
  { prefix: "+965", country: "Kuwait", code: "KW", flag: "🇰🇼" },
  { prefix: "+966", country: "Saudi Arabia", code: "SA", flag: "🇸🇦" },
  { prefix: "+967", country: "Yemen", code: "YE", flag: "🇾🇪" },
  { prefix: "+968", country: "Oman", code: "OM", flag: "🇴🇲" },
  { prefix: "+970", country: "Palestine", code: "PS", flag: "🇵🇸" },
  { prefix: "+971", country: "United Arab Emirates", code: "AE", flag: "🇦🇪" },
  { prefix: "+972", country: "Israel", code: "IL", flag: "🇮🇱" },
  { prefix: "+973", country: "Bahrain", code: "BH", flag: "🇧🇭" },
  { prefix: "+974", country: "Qatar", code: "QA", flag: "🇶🇦" },
  { prefix: "+975", country: "Bhutan", code: "BT", flag: "🇧🇹" },
  { prefix: "+976", country: "Mongolia", code: "MN", flag: "🇲🇳" },
  { prefix: "+977", country: "Nepal", code: "NP", flag: "🇳🇵" },
  { prefix: "+98", country: "Iran", code: "IR", flag: "🇮🇷" },
  { prefix: "+992", country: "Tajikistan", code: "TJ", flag: "🇹🇯" },
  { prefix: "+993", country: "Turkmenistan", code: "TM", flag: "🇹🇲" },
  { prefix: "+994", country: "Azerbaijan", code: "AZ", flag: "🇦🇿" },
  { prefix: "+995", country: "Georgia", code: "GE", flag: "🇬🇪" },
  { prefix: "+996", country: "Kyrgyzstan", code: "KG", flag: "🇰🇬" },
  { prefix: "+998", country: "Uzbekistan", code: "UZ", flag: "🇺🇿" },
];

const sortedPrefixes = [...phoneCountryCodes].sort((a, b) => b.prefix.length - a.prefix.length);

export function detectCountryFromPhone(phone: string): CountryPhoneInfo | null {
  if (!phone) return null;
  
  const cleaned = phone.replace(/[\s\-\(\)]/g, "");
  
  if (!cleaned.startsWith("+")) {
    if (cleaned.startsWith("00")) {
      const withPlus = "+" + cleaned.substring(2);
      return detectCountryFromPhone(withPlus);
    }
    if (cleaned.startsWith("60") && cleaned.length >= 10) {
      return detectCountryFromPhone("+" + cleaned);
    }
    return null;
  }
  
  for (const country of sortedPrefixes) {
    if (cleaned.startsWith(country.prefix)) {
      return country;
    }
  }
  
  return null;
}

export function getCountryIndicatorText(phone: string): string | null {
  const country = detectCountryFromPhone(phone);
  if (!country) return null;
  return `${country.flag} Possibly from ${country.country}`;
}
