const path = require('path');
const root = path.resolve(__dirname);
const logs = path.join(root, 'logs');

module.exports = {
  apps: [
    {
      name: 'pelangi-server',
      script: 'npm',
      args: ['run', 'dev:server'],
      cwd: root,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: { NODE_ENV: 'development' },
      error_file: path.join(logs, 'pelangi-server-error.log'),
      out_file: path.join(logs, 'pelangi-server-out.log'),
      merge_logs: true,
    },
    {
      name: 'pelangi-frontend',
      script: 'npm',
      args: ['run', 'dev:frontend'],
      cwd: root,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: { NODE_ENV: 'development' },
      error_file: path.join(logs, 'pelangi-frontend-error.log'),
      out_file: path.join(logs, 'pelangi-frontend-out.log'),
      merge_logs: true,
    },
    {
      name: 'pelangi-rainbow',
      script: 'npm',
      args: ['run', 'dev:pelangi-rainbow'],
      cwd: root,
      // → Rainbow AI on http://localhost:3002 (MCP_SERVER_PORT from .env.pelangi.local)
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: { NODE_ENV: 'development' },
      error_file: path.join(logs, 'pelangi-rainbow-error.log'),
      out_file: path.join(logs, 'pelangi-rainbow-out.log'),
      merge_logs: true,
    },
    {
      name: 'southern-server',
      script: 'npm',
      args: ['run', 'dev:southern-server'],
      cwd: root,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: { NODE_ENV: 'development' },
      error_file: path.join(logs, 'southern-server-error.log'),
      out_file: path.join(logs, 'southern-server-out.log'),
      merge_logs: true,
    },
    {
      name: 'southern-frontend',
      script: 'npm',
      args: ['run', 'dev:southern-frontend'],
      cwd: root,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: { NODE_ENV: 'development' },
      error_file: path.join(logs, 'southern-frontend-error.log'),
      out_file: path.join(logs, 'southern-frontend-out.log'),
      merge_logs: true,
    },
    {
      name: 'southern-rainbow',
      script: 'npm',
      args: ['run', 'dev:southern-rainbow'],
      cwd: root,
      // → Rainbow AI on http://localhost:8002 (MCP_SERVER_PORT from .env.southern.local)
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: { NODE_ENV: 'development' },
      error_file: path.join(logs, 'southern-rainbow-error.log'),
      out_file: path.join(logs, 'southern-rainbow-out.log'),
      merge_logs: true,
    },
    {
      name: 'fleet-manager',
      script: 'server.js',
      cwd: path.join(root, 'fleet-manager'),
      node_args: '--max-old-space-size=128',
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 9999 },
      autorestart: true,
      max_restarts: 15,
      restart_delay: 3000,
      max_memory_restart: '150M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: path.join(logs, 'fleet-manager-error.log'),
      out_file: path.join(logs, 'fleet-manager-out.log'),
      merge_logs: true,
      min_uptime: '5s',
      listen_timeout: 8000,
    },
  ],
};
